version: '3'
services:
  openobserve:
    image: public.ecr.aws/zinclabs/openobserve:latest
    container_name: openobserve
    ports:
      - 5080:5080
    volumes:
      - openobserve-data:/data
    env_file:
      - services/openobserve/.env

  minio:
    image: quay.io/minio/minio:latest
    container_name: minio
    ports:
      - 19000:19000
    command: server /data
    volumes:
      - minio-backet:/data
    env_file:
      - services/minio/.env

  minio-setup:
    image: minio/mc:latest
    depends_on:
      - minio
    volumes:
      - ./services/minio/entrypoint.sh:/entrypoint.sh
    entrypoint: /entrypoint.sh

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./services/prometheus:/etc/prometheus
    command: "--config.file=/etc/prometheus/prometheus.yml"

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.47.1
    container_name: cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    devices:
      - /dev/kmsg:/dev/kmsg
    privileged: true

volumes:
  openobserve-data:
  minio-backet:
